# Site
repository: MHassanNadeem/MHassanNadeem.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hassan Nadeem
title: Software Engineer
email: me@HassanNadeem.com
website: HassanNadeem.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: mhassannadeem
github_username:  mhassannadeem
instagram_username: mhassannadeem
linkedin_username: mhassannadeem
youtube_username: hassannadeem

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hassan and I'm a software and hardware engineer. I have designed various products all the way from pcb layouts to writing code. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark> and <mark>C</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Bloomberg L.P.
        link: bloomberg.com
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: July 2019 - Present
        quote: >
          Worked in a team as a full stack engineer to support Bloomberg Enterprise Access Point, eap.bloomberg.com. Serves >2M API requests/day.
        description: | # this will include new lines to allow paragraphs
            - Built multiple backend <mark>RestAPI</mark> micro-services using <mark>Python</mark>, <mark>Flask</mark>, <mark>FastApi</mark>, <mark>Gunicorn</mark>, <mark>Apache Solr</mark> and <mark>Apache Kafka</mark>.
            - Created UI components using <mark>node</mark>, <mark>Express</mark>, <mark>TypeScript<mark> and <mark>React</mark>.
            - Spearheaded the delivery of various features from technical design, development, deployment to maintenance.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Virginia Tech
        caption: August 2017 - May 2019
        sub_title: M.S. Computer Science
        quote: >
          Got degree in Computer Science but did my thesis with Computer Engineering Department. I was also employed part-time as a research assistant.
        description: | # this will include new lines to allow paragraphs
          GPA: 3.78. Courses: Linux Kernel Programming, Computer Architecture, Multiprocessor Programming, Systems Security, Data Analytics, Info Visualization, Urban Computing
      - layout: left
        title: LUMS
        caption: August 2011 - May 2015
        sub_title: B.S. Electrical Engineering
        quote: >
          I was also employed part-time as a teaching assistant.
        description: | # this will include new lines to allow paragraphs
          GPA 3.35. Courses: Microcontrollers and Interfacing, Embedded Systems, Computer Networks, Data Structures

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
